### ISSUE TITLE
RapidBlink blinks the same speed as SlowBlink

### ISSUE THREAD

**Issue by cliftonfoster** [k-iro/PastelEx#1]
I like what you've done with PastelEx. I was just playing with it and the different decorations. The RapidBlink and the SlowBlink blink at the same rate. Am I doing something wrong?

```
Console.WriteLine($"this text {"Slow blinking".Deco(Decoration.SlowBlink)}!");
Console.WriteLine($"this text {"Rapid blinking".Deco(Decoration.RapidBlink)}!");
```

**Comment by k-iro** [comment]
Actually, this depends on the current terminal. Both have different codes, so they aren't the same.

> ![image](https://github.com/k-iro/PastelEx/assets/88717056/c9ae5579-b0ec-441f-a7dd-0648547849da)
From [Wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code).

I think if your terminal doesn't support rapid blinking, then it uses slow blinking.

**Comment by cliftonfoster** [comment]
Thank you for the explanation and the article link.
